import {forwardIssue} from './issue-mail.js';
// Optional public API for a GitHub Pages copy. Never place mail secrets in the frontend.
// Cloudflare Worker bindings: DB (D1), ALLOWED_ORIGINS, RESEND_API_KEY,
// ISSUE_REPORT_FROM (verified sender), ISSUE_REPORT_TO (private destination).
const places={Auckland:[-36.8485,174.7633],Hamilton:[-37.787,175.2793],Wellington:[-41.2866,174.7756],Christchurch:[-43.5321,172.6362],Dunedin:[-45.8742,170.5036],Invercargill:[-46.4132,168.3538],Tauranga:[-37.6878,176.1651],Rotorua:[-38.1368,176.2497],Queenstown:[-45.0312,168.6626],Nelson:[-41.2706,173.284],Whangārei:[-35.7251,174.3237],Kerikeri:[-35.228,173.9474],Taupō:[-38.6857,176.0702],Gisborne:[-38.6623,178.0176],Napier:[-39.4928,176.912],Hastings:[-39.6381,176.8492],'New Plymouth':[-39.0556,174.0752],Whanganui:[-39.9333,175.05],'Palmerston North':[-40.3523,175.6082],Blenheim:[-41.5134,173.9612],Westport:[-41.7526,171.6037],Greymouth:[-42.4504,171.2108],Timaru:[-44.3967,171.255],Wanaka:[-44.696,169.136]};
const dateNZ=(time=new Date())=>{const p=new Intl.DateTimeFormat('en-NZ',{timeZone:'Pacific/Auckland',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(time);return ['year','month','day'].map(k=>p.find(x=>x.type===k).value).join('-')};
const plain=s=>s.replace(/<[^>]*>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
function metCode(symbol){if(symbol.includes('thunder'))return 95;if(symbol.includes('snow')||symbol.includes('sleet'))return 71;if(symbol.includes('rain'))return 61;if(symbol.includes('fog'))return 45;if(symbol.startsWith('clearsky'))return 0;if(symbol.startsWith('fair'))return 1;if(symbol.startsWith('partlycloudy'))return 2;return 3}
function validDate(s){return /^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s+'T12:00:00Z'))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s}
export default {async fetch(request,env,ctx){const origin=request.headers.get('Origin'),allowed=(env.ALLOWED_ORIGINS||'').split(',').map(s=>s.trim()).filter(Boolean),headers={'Content-Type':'application/json','Cache-Control':'no-store','Vary':'Origin'};if(!origin||!allowed.includes(origin))return Response.json({error:'This website is not connected to this service.'},{status:403});Object.assign(headers,{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type'});const reply=(body,status=200)=>new Response(JSON.stringify(body),{status,headers});if(request.method==='OPTIONS')return new Response(null,{status:204,headers});const url=new URL(request.url),path=url.pathname,p=url.searchParams;
try{
if(path==='/api/weather'&&request.method==='GET'){const name=p.get('location')||'Auckland',key=Object.keys(places).find(k=>k.toLowerCase()===name.toLowerCase());if(!key)return reply({error:'Choose one of the listed New Zealand towns.'},400);const [lat,lon]=places[key],remote='https://api.met.no/weatherapi/locationforecast/2.0/compact?'+new URLSearchParams({lat:lat.toFixed(4),lon:lon.toFixed(4)}),cacheKey=new Request(remote),cache=caches.default;let response=await cache.match(cacheKey);if(!response){response=await fetch(remote,{headers:{'User-Agent':'TheJamesNZ/1.0 ('+origin+')','Accept':'application/json'},signal:AbortSignal.timeout(12000)});if(!response.ok)return reply({error:'Live weather is unavailable. Retry shortly or open MetService.'},503);const cached=new Response(response.clone().body,{headers:{'Content-Type':'application/json','Cache-Control':'public,max-age=1800'}});ctx.waitUntil(cache.put(cacheKey,cached))}const d=await response.json(),series=d.properties?.timeseries;if(!Array.isArray(series)||!series.length)return reply({error:'Live weather is incomplete.'},503);const now=Date.now(),current=series.reduce((a,b)=>Math.abs(Date.parse(a.time)-now)<Math.abs(Date.parse(b.time)-now)?a:b),today=dateNZ(),rows=series.filter(x=>dateNZ(new Date(x.time))===today);if(!rows.length||Math.abs(Date.parse(current.time)-now)>10800000)return reply({error:'A current live forecast is unavailable.'},503);const values=current.data.instant.details,temps=rows.map(x=>x.data.instant.details.air_temperature);return reply({place:key,region:'New Zealand',date:today,updated:d.properties.meta.updated_at,source:'MET Norway · CC BY 4.0',rangeLabel:'Forecast through tonight',current:{temperature_2m:values.air_temperature,apparent_temperature:null,weather_code:metCode(current.data.next_1_hours?.summary?.symbol_code||current.data.next_6_hours?.summary?.symbol_code||''),wind_speed_10m:values.wind_speed*3.6,precipitation:current.data.next_1_hours?.details.precipitation_amount||0,time:current.time},daily:{high:Math.max(...temps),low:Math.min(...temps),rain:null,uv:null,rainExpected:rows.some(x=>(x.data.next_1_hours?.details.precipitation_amount||0)>.1)},hourly:series.filter(x=>Date.parse(x.time)>=now-3600000).slice(0,12).map(x=>({time:x.time,temperature:x.data.instant.details.air_temperature,rain:x.data.next_1_hours?.details.precipitation_amount??null,wind:x.data.instant.details.wind_speed*3.6}))})}
if(path==='/api/gospel'&&request.method==='GET'){const date=p.get('date')||dateNZ();if(!validDate(date))return reply({error:'Choose a valid date.'},400);const official='https://www.vaticannews.va/en/word-of-the-day/'+date.replaceAll('-','/')+'.html';let ref=date==='2026-10-07'?{book:'Luke',chapter:11,range:'1-4'}:null;try{const response=await fetch(official,{signal:AbortSignal.timeout(9000)});if(response.ok){const html=await response.text(),text=plain(html.split(/Gospel of the day/i)[1]?.split(/The words of the Popes/i)[0]||''),m=text.match(/(?:according to|Gospel (?:of|according to))\s*(?:Saint\s*|St\.\s*)?(Matthew|Mark|Luke|John)\s*(\d{1,3})\s*[:,]\s*([\d\s,;.\-–]+)/i);if(m)ref={book:m[1],chapter:Number(m[2]),range:m[3].trim().replace(/[.,;\s]+$/,'')}}}catch{}return reply(ref?{url:official,reference:ref.book+' '+ref.chapter+':'+ref.range,book:ref.book,chapter:ref.chapter,range:ref.range,verses:[]}:{url:official,error:'Open the official daily reading for this date. No unverified reference is shown.'})}
if(path==='/api/feedback'&&request.method==='GET'){if(p.get('kind')==='issue')return reply({error:'Issue reports are private.'},403);if(!env.DB)return reply({error:'The feedback database is not connected.'},503);const rows=await env.DB.prepare("SELECT id,name,message,rating,created FROM feedback WHERE kind='review' ORDER BY created DESC LIMIT 50").all();return reply({items:rows.results})}
if(path==='/api/feedback'&&request.method==='POST'){if(!env.DB)return reply({error:'The feedback database is not connected. Your message has not been sent.'},503);if(Number(request.headers.get('content-length')||0)>20000)return reply({error:'Your message is too long.'},413);const raw=await request.text();if(raw.length>20000)return reply({error:'Your message is too long.'},413);let body;try{body=JSON.parse(raw)}catch{return reply({error:'Please submit a valid form.'},400)}if(!body||typeof body!=='object'||Array.isArray(body))return reply({error:'Please submit a valid form.'},400);const {kind,name='',message,rating}=body;if(!['issue','review'].includes(kind)||typeof name!=='string'||name.length>100||typeof message!=='string'||message.trim().length<5||message.length>4000||kind==='review'&&(!Number.isInteger(rating)||rating<1||rating>5))return reply({error:'Add a valid message of 5–4,000 characters and a rating from 1 to 5 for reviews.'},400);const now=Date.now(),identity=request.headers.get('CF-Connecting-IP')||'unknown',hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(identity))),b=>b.toString(16).padStart(2,'0')).join(''),bucket=hash+':'+Math.floor(now/600000);const quota=await env.DB.prepare('INSERT INTO feedback_rate(bucket,count,expires) VALUES(?,1,?) ON CONFLICT(bucket) DO UPDATE SET count=count+1 RETURNING count').bind(bucket,now+1200000).first();if(!quota||quota.count>5)return reply({error:'Please wait a few minutes before submitting again.'},429);ctx.waitUntil(env.DB.prepare('DELETE FROM feedback_rate WHERE expires < ?').bind(now).run());const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO feedback(id,kind,name,message,rating,created) VALUES(?,?,?,?,?,?)').bind(id,kind,name.trim()||'Community member',message.trim(),kind==='review'?rating:null,now).run();if(kind==='review')return reply({id,saved:true});const result=await forwardIssue(env,{id,name:name.trim()||'Community member',message:message.trim()},origin+'/');try{await env.DB.prepare('INSERT INTO feedback_delivery(feedback_id,status,updated) VALUES(?,?,?)').bind(id,result.delivery,now).run()}catch{}return reply({id,saved:true,...result})}
return reply({error:'Service not found.'},404);
}catch{return reply({error:'The service could not complete this request. Your form text is still here; please retry.'},503)}
}};
